INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (1, "MARCÍLIO", 1991);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (2, "MARIO", 1961);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (3, "MÁRCIO", 1988);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (4, "LAÍS", 1994);

ALTER SEQUENCE pessoa_deq RESTART WITH 5;